### ISSUE TITLE
Execution Steps

### ISSUE THREAD

**Issue by Shiny128** [kjsr7/Anomaly_Detection#1]
Hello Sir , 
Please give me step wise execution details inorder to view the demo of this project.
I am new to programming and I am unable to identify the sequence of execution and how to make use of the iteration graph.

**Comment by Shiny128** [comment]
When I tried Executing Demo_GUI.py ,I got the following error

Using Theano backend.
Traceback (most recent call last):
  File "Demo_GUI.py", line 241, in <module>
    main()
  File "Demo_GUI.py", line 237, in main
    w = PrettyWidget()
  File "Demo_GUI.py", line 126, in __init__
    self.initUI()
  File "Demo_GUI.py", line 139, in initUI
    model = load_model(model_path)
  File "Demo_GUI.py", line 38, in load_model
    model = model_from_json(open(json_path).read())
FileNotFoundError: [Errno 2] No such file or directory: '/home/cvlab/Waqas_Data/Anomaly_Data/Pre_TrainedModels/L1L2/model.json'

Please guide the steps to fix this error

**Comment by FatimaDua** [comment]
have you been able to solve this issue?
